# Generated by Django 5.0.6 on 2025-10-21 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='barangay',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='case_solve_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='case_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_accidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accident',
            name='date_reported',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='incident_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='municipal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='offense',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='offense_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='ppo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PPO'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='pro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PRO'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='stage_of_felony',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='station',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time_committed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time_reported',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='type_of_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type of Place'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='vehicle_kind',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='vehicle_plate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
