# Generated by Django 5.0.6 on 2025-10-30 05:43
# Performance optimization migration - adds database indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0002_alter_accident_barangay_and_more"),
    ]

    operations = [
        # ==================================================================
        # ACCIDENT MODEL INDEXES
        # ==================================================================

        # Spatial indexes for map queries
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['latitude', 'longitude'], name='accident_lat_lng_idx'),
        ),

        # Temporal indexes for date filtering
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['-date_committed'], name='accident_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['year'], name='accident_year_idx'),
        ),

        # Location indexes for geographic filtering
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['province'], name='accident_province_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['municipal'], name='accident_municipal_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['province', 'municipal'], name='accident_location_idx'),
        ),

        # Cluster-related indexes
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['cluster_id'], name='accident_cluster_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['is_hotspot'], name='accident_hotspot_idx'),
        ),

        # Incident type indexes for statistics
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['incident_type'], name='accident_type_idx'),
        ),

        # Victim-related indexes for casualty filtering
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['victim_killed'], name='accident_killed_idx'),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(fields=['victim_injured'], name='accident_injured_idx'),
        ),

        # Composite index for common queries
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(
                fields=['province', '-date_committed'],
                name='accident_prov_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='accident',
            index=models.Index(
                fields=['is_hotspot', '-date_committed'],
                name='accident_hotspot_date_idx'
            ),
        ),

        # ==================================================================
        # ACCIDENT CLUSTER MODEL INDEXES
        # ==================================================================

        # Severity index for hotspot ranking
        migrations.AddIndex(
            model_name='accidentcluster',
            index=models.Index(fields=['-severity_score'], name='cluster_severity_idx'),
        ),

        # Spatial indexes for cluster center
        migrations.AddIndex(
            model_name='accidentcluster',
            index=models.Index(
                fields=['center_latitude', 'center_longitude'],
                name='cluster_center_idx'
            ),
        ),

        # Accident count index
        migrations.AddIndex(
            model_name='accidentcluster',
            index=models.Index(fields=['-accident_count'], name='cluster_count_idx'),
        ),

        # Location index
        migrations.AddIndex(
            model_name='accidentcluster',
            index=models.Index(fields=['primary_location'], name='cluster_location_idx'),
        ),

        # ==================================================================
        # ACCIDENT REPORT MODEL INDEXES
        # ==================================================================

        # Status index for filtering pending reports
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['status'], name='report_status_idx'),
        ),

        # Date indexes for chronological sorting
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['-created_at'], name='report_created_idx'),
        ),
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['-incident_date'], name='report_incident_idx'),
        ),

        # Location indexes
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['province'], name='report_province_idx'),
        ),

        # Composite index for admin queries
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(
                fields=['status', '-created_at'],
                name='report_status_date_idx'
            ),
        ),
    ]
