# Generated by Django 5.0.6 on 2025-10-30 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0003_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("login_failed", "Failed Login Attempt"),
                            ("password_change", "Password Changed"),
                            ("accident_create", "Accident Created"),
                            ("accident_edit", "Accident Edited"),
                            ("accident_delete", "Accident Deleted"),
                            ("accident_view", "Accident Viewed"),
                            ("user_create", "User Created"),
                            ("user_edit", "User Edited"),
                            ("user_delete", "User Deleted"),
                            ("user_activate", "User Activated"),
                            ("user_deactivate", "User Deactivated"),
                            ("clustering_run", "Clustering Executed"),
                            ("report_generate", "Report Generated"),
                            ("export_data", "Data Exported"),
                            ("system_config", "System Configuration Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("station", models.CharField(blank=True, max_length=200, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("object_id", models.IntegerField(blank=True, null=True)),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("changes", models.JSONField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Badge/ID Number"
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("PGEN", "Police General"),
                            ("PLTGEN", "Police Lieutenant General"),
                            ("PMGEN", "Police Major General"),
                            ("PBGEN", "Police Brigadier General"),
                            ("PCOLONEL", "Police Colonel"),
                            ("PLTCOL", "Police Lieutenant Colonel"),
                            ("PMAJOR", "Police Major"),
                            ("PCAPTAIN", "Police Captain"),
                            ("PLIEUTENANT", "Police Lieutenant"),
                            (
                                "PEXECUTIVE MASTER SERGEANT",
                                "Police Executive Master Sergeant",
                            ),
                            ("PCHIEF MASTER SERGEANT", "Police Chief Master Sergeant"),
                            (
                                "PSENIOR MASTER SERGEANT",
                                "Police Senior Master Sergeant",
                            ),
                            ("PMASTER SERGEANT", "Police Master Sergeant"),
                            ("PSTAFF SERGEANT", "Police Staff Sergeant"),
                            ("PCORPORAL", "Police Corporal"),
                            ("PATROLMAN", "Patrolman"),
                            ("CIVILIAN", "Civilian Personnel"),
                        ],
                        default="PATROLMAN",
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("regional_director", "Regional Director"),
                            ("provincial_chief", "Provincial Chief"),
                            ("station_commander", "Station Commander"),
                            ("traffic_officer", "Traffic Officer"),
                            ("data_encoder", "Data Encoder"),
                        ],
                        default="traffic_officer",
                        max_length=30,
                    ),
                ),
                ("region", models.CharField(default="CARAGA", max_length=100)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("station", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Unit/Office",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("mobile_number", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("must_change_password", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
                "ordering": ["rank", "user__last_name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_lat_lng_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_date_desc_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_year_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_province_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_municipal_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_location_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_cluster_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_hotspot_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_killed_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_injured_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_prov_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="accident",
            name="accident_hotspot_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentcluster",
            name="cluster_severity_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentcluster",
            name="cluster_center_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentcluster",
            name="cluster_count_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentcluster",
            name="cluster_location_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentreport",
            name="report_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentreport",
            name="report_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentreport",
            name="report_incident_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentreport",
            name="report_province_idx",
        ),
        migrations.RemoveIndex(
            model_name="accidentreport",
            name="report_status_date_idx",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="audit_logs_user_id_e11c73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="audit_logs_action_f48619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
            ),
        ),
    ]
