# Generated by Claude Code on 2025-11-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0004_auditlog_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
