# Generated by Django 5.0.6 on 2025-12-03 04:01

import accidents.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0005_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accident",
            name="date_committed",
            field=models.DateField(
                help_text="Date when accident occurred",
                validators=[accidents.validators.validate_date_not_future],
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="date_reported",
            field=models.DateField(
                blank=True,
                help_text="Date when accident was reported",
                null=True,
                validators=[accidents.validators.validate_date_not_future],
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7,
                help_text="Latitude in decimal degrees (Philippine bounds: 4.0° to 22.0° N)",
                max_digits=10,
                validators=[accidents.validators.validate_philippine_latitude],
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7,
                help_text="Longitude in decimal degrees (Philippine bounds: 115.0° to 128.0° E)",
                max_digits=10,
                validators=[accidents.validators.validate_philippine_longitude],
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="suspect_count",
            field=models.IntegerField(
                default=0,
                help_text="Total number of suspects (0-50)",
                validators=[
                    accidents.validators.validate_suspect_count,
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="time_committed",
            field=models.TimeField(
                blank=True, help_text="Time when accident occurred", null=True
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="time_reported",
            field=models.TimeField(
                blank=True, help_text="Time when accident was reported", null=True
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="victim_count",
            field=models.IntegerField(
                default=0,
                help_text="Total number of victims (0-100)",
                validators=[
                    accidents.validators.validate_casualty_count,
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="victim_injured",
            field=models.BooleanField(
                default=False, help_text="At least one victim was injured"
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="victim_killed",
            field=models.BooleanField(
                default=False, help_text="At least one victim was killed"
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="victim_unharmed",
            field=models.BooleanField(
                default=False, help_text="No victims were harmed"
            ),
        ),
        migrations.AlterField(
            model_name="accident",
            name="year",
            field=models.IntegerField(
                blank=True,
                help_text="Year of accident (1950-present)",
                null=True,
                validators=[accidents.validators.validate_year_range],
            ),
        ),
        migrations.AlterField(
            model_name="accidentcluster",
            name="accident_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of accidents in this cluster",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="accidentcluster",
            name="distance_threshold",
            field=models.FloatField(
                help_text="Distance threshold in decimal degrees (0.001-1.0)",
                validators=[accidents.validators.validate_cluster_distance_threshold],
            ),
        ),
        migrations.AlterField(
            model_name="accidentcluster",
            name="severity_score",
            field=models.FloatField(
                default=0.0,
                help_text="Calculated severity score (0-1000)",
                validators=[accidents.validators.validate_severity_score],
            ),
        ),
        migrations.AlterField(
            model_name="accidentcluster",
            name="total_casualties",
            field=models.IntegerField(
                default=0,
                help_text="Total casualties across all accidents in cluster",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="casualties_injured",
            field=models.IntegerField(
                default=0,
                help_text="Number of injured persons",
                validators=[
                    accidents.validators.validate_casualty_count,
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="casualties_killed",
            field=models.IntegerField(
                default=0,
                help_text="Number of fatalities",
                validators=[
                    accidents.validators.validate_casualty_count,
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="incident_date",
            field=models.DateField(
                help_text="Date of the accident",
                validators=[accidents.validators.validate_date_not_future],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="incident_description",
            field=models.TextField(help_text="Detailed description of the accident"),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="incident_time",
            field=models.TimeField(help_text="Time of the accident"),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7,
                help_text="Latitude coordinate",
                max_digits=10,
                validators=[accidents.validators.validate_philippine_latitude],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7,
                help_text="Longitude coordinate",
                max_digits=10,
                validators=[accidents.validators.validate_philippine_longitude],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="photo_1",
            field=models.ImageField(
                blank=True,
                help_text="Photo of accident scene (max 5MB, jpg/png)",
                null=True,
                upload_to="accident_reports/",
                validators=[
                    accidents.validators.validate_image_file_size,
                    accidents.validators.validate_image_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="photo_2",
            field=models.ImageField(
                blank=True,
                help_text="Additional photo (max 5MB, jpg/png)",
                null=True,
                upload_to="accident_reports/",
                validators=[
                    accidents.validators.validate_image_file_size,
                    accidents.validators.validate_image_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="accidentreport",
            name="photo_3",
            field=models.ImageField(
                blank=True,
                help_text="Additional photo (max 5MB, jpg/png)",
                null=True,
                upload_to="accident_reports/",
                validators=[
                    accidents.validators.validate_image_file_size,
                    accidents.validators.validate_image_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--- Select Unit ---"),
                    (
                        "R1 - Regional Personnel and Records Management Division",
                        "R1 - Regional Personnel and Records Management Division",
                    ),
                    (
                        "R2 - Regional Intelligence Division",
                        "R2 - Regional Intelligence Division",
                    ),
                    (
                        "R3 - Regional Operation Management Division",
                        "R3 - Regional Operation Management Division",
                    ),
                    (
                        "R4 - Regional Logistics Research Development Division",
                        "R4 - Regional Logistics Research Development Division",
                    ),
                    (
                        "R5 - Regional Community Affairs Development Division",
                        "R5 - Regional Community Affairs Development Division",
                    ),
                    (
                        "R6 - Regional Comptrollership Division",
                        "R6 - Regional Comptrollership Division",
                    ),
                    (
                        "R7 - Regional Investigation Detective Management Division",
                        "R7 - Regional Investigation Detective Management Division",
                    ),
                    (
                        "R8 - Regional Learning and Doctrine Development Division",
                        "R8 - Regional Learning and Doctrine Development Division",
                    ),
                    (
                        "R9 - Regional Plans and Strategy Management Division",
                        "R9 - Regional Plans and Strategy Management Division",
                    ),
                    (
                        "Regional Headquarters Support Unit",
                        "Regional Headquarters Support Unit",
                    ),
                    (
                        "Regional Information and Communication Technology Management Division",
                        "Regional Information and Communication Technology Management Division",
                    ),
                    ("Regional Health Service", "Regional Health Service"),
                    ("Public Information Office", "Public Information Office"),
                    (
                        "Surigao del Norte Police Provincial Office",
                        "Surigao del Norte Police Provincial Office",
                    ),
                    (
                        "Surigao del Sur Police Provincial Office",
                        "Surigao del Sur Police Provincial Office",
                    ),
                    (
                        "Agusan del Norte Police Provincial Office",
                        "Agusan del Norte Police Provincial Office",
                    ),
                    (
                        "Agusan del Sur Police Provincial Office",
                        "Agusan del Sur Police Provincial Office",
                    ),
                    ("Butuan City Police Office", "Butuan City Police Office"),
                ],
                max_length=200,
                null=True,
                verbose_name="Unit/Office",
            ),
        ),
        migrations.CreateModel(
            name="ClusterValidationMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clustering_date", models.DateTimeField(auto_now_add=True)),
                (
                    "num_clusters",
                    models.IntegerField(
                        help_text="Number of clusters in this analysis",
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "total_accidents",
                    models.IntegerField(
                        help_text="Total accidents analyzed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "silhouette_score",
                    models.FloatField(
                        blank=True,
                        help_text="Silhouette Score: -1 to 1, higher is better (measures cluster cohesion)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "davies_bouldin_index",
                    models.FloatField(
                        blank=True,
                        help_text="Davies-Bouldin Index: 0 to ∞, lower is better (measures cluster separation)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "calinski_harabasz_score",
                    models.FloatField(
                        blank=True,
                        help_text="Calinski-Harabasz Score: 0 to ∞, higher is better (variance ratio)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "cluster_quality",
                    models.CharField(
                        blank=True,
                        help_text="Overall cluster quality assessment (Excellent, Good, Fair, Poor)",
                        max_length=20,
                    ),
                ),
                ("linkage_method", models.CharField(default="complete", max_length=20)),
                (
                    "distance_threshold",
                    models.FloatField(
                        help_text="Distance threshold used in clustering",
                        validators=[
                            accidents.validators.validate_cluster_distance_threshold
                        ],
                    ),
                ),
                (
                    "clustering_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_metrics",
                        to="accidents.clusteringjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster Validation Metric",
                "verbose_name_plural": "Cluster Validation Metrics",
                "db_table": "cluster_validation_metrics",
                "ordering": ["-clustering_date"],
            },
        ),
    ]
