# Generated by Django 5.0.6 on 2026-01-30 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0006_alter_accident_date_committed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='driver_age',
            field=models.IntegerField(blank=True, help_text='Age of primary driver (0-150)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='accident',
            name='driver_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown/Not Specified')], default='UNKNOWN', help_text='Gender of primary driver/suspect involved in accident', max_length=10),
        ),
        migrations.AddField(
            model_name='accident',
            name='victim_age',
            field=models.IntegerField(blank=True, help_text='Age of primary victim (0-150)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='accident',
            name='victim_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown/Not Specified')], default='UNKNOWN', help_text='Gender of primary victim involved in accident', max_length=10),
        ),
    ]
