# Generated by Django 5.0.6 on 2026-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0007_accident_driver_age_accident_driver_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True),
        ),
    ]
