# Generated by Django 5.0.6 on 2026-02-06 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0009_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='driver_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='driver_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='incident_type',
            field=models.CharField(choices=[('VEHICULAR_ACCIDENT', 'Vehicular Accident'), ('HIT_AND_RUN', 'Hit and Run'), ('RECKLESS_DRIVING', 'Reckless Driving'), ('ROAD_COLLISION', 'Road Collision'), ('PEDESTRIAN_ACCIDENT', 'Pedestrian Accident'), ('OTHER', 'Other')], default='VEHICULAR_ACCIDENT', max_length=200),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='suspect_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='suspect_details',
            field=models.TextField(blank=True, help_text='Suspect/Driver information', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='type_of_place',
            field=models.CharField(blank=True, choices=[('ALONG_STREET', 'Along the street'), ('HIGHWAY', 'Highway'), ('INTERSECTION', 'Intersection'), ('BRIDGE', 'Bridge'), ('CURVE_BEND', 'Curve/Bend'), ('PARKING_AREA', 'Parking Area'), ('RESIDENTIAL', 'Residential Area'), ('OTHER', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_kind',
            field=models.CharField(blank=True, choices=[('MOTORCYCLE', 'Motorcycle'), ('TRICYCLE', 'Tricycle'), ('CAR', 'Car/Sedan'), ('SUV', 'SUV/Pickup'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('JEEPNEY', 'Jeepney'), ('BICYCLE', 'Bicycle'), ('PEDESTRIAN', 'Pedestrian (No Vehicle)'), ('OTHER', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='e.g., Toyota, Honda, Yamaha', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='e.g., Vios, City, Mio', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_plate_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victim_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victim_details',
            field=models.TextField(blank=True, help_text='Victim information (Name, Age, Gender, Status)', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victim_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='vehicles_involved',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
