# Generated by Django 5.0.6 on 2026-02-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0010_overhaul_accident_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentreport',
            name='suspect_details',
        ),
        migrations.RemoveField(
            model_name='accidentreport',
            name='victim_details',
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='suspect_name',
            field=models.CharField(blank=True, help_text='Full name of suspect/driver', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victim_name',
            field=models.CharField(blank=True, help_text='Full name of victim', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victim_status',
            field=models.CharField(blank=True, choices=[('KILLED', 'Killed'), ('INJURED', 'Injured'), ('UNHARMED', 'Unharmed')], max_length=20, null=True),
        ),
    ]
