# Generated by Django 5.0.6 on 2026-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0011_replace_details_with_separate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='incident_type_other',
            field=models.CharField(blank=True, help_text='Specify if Other is selected', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='type_of_place_other',
            field=models.CharField(blank=True, help_text='Specify if Other is selected', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_kind_other',
            field=models.CharField(blank=True, help_text='Specify if Other is selected', max_length=200, null=True),
        ),
    ]
