# Generated by Django 5.0.6 on 2026-02-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0012_add_other_specification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_make_other',
            field=models.CharField(blank=True, help_text='Specify if Other brand', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_model_other',
            field=models.CharField(blank=True, help_text='Specify if Other model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='vehicle_make',
            field=models.CharField(blank=True, choices=[('TOYOTA', 'Toyota'), ('MITSUBISHI', 'Mitsubishi'), ('HONDA', 'Honda'), ('SUZUKI', 'Suzuki'), ('FORD', 'Ford'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('ISUZU', 'Isuzu'), ('CHEVROLET', 'Chevrolet'), ('YAMAHA', 'Yamaha'), ('KAWASAKI', 'Kawasaki'), ('RUSI', 'Rusi'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('SUBARU', 'Subaru'), ('MAZDA', 'Mazda'), ('VOLKSWAGEN', 'Volkswagen'), ('BYD', 'BYD'), ('GEELY', 'Geely'), ('CHERY', 'Chery'), ('MG', 'MG'), ('GAC', 'GAC'), ('CHANGAN', 'Changan'), ('FOTON', 'Foton'), ('HINO', 'Hino'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
