# Generated by Django 5.0.6 on 2026-02-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0013_add_vehicle_make_model_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
