# Generated by Django 5.0.6 on 2026-02-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0014_remove_vehicle_make_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='suspects_data',
            field=models.JSONField(blank=True, default=list, help_text='List of suspects [{name, age, gender, status, nationality, occupation}]'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victims_data',
            field=models.JSONField(blank=True, default=list, help_text='List of victims [{name, age, gender, status, nationality, occupation}]'),
        ),
    ]
