# Generated by Django 5.0.6 on 2026-02-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0015_add_victims_suspects_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='offense',
            field=models.TextField(blank=True, help_text='Offense description', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='offense_type',
            field=models.CharField(blank=True, help_text='Type of offense', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='stage_of_felony',
            field=models.CharField(blank=True, choices=[('ATTEMPTED', 'Attempted'), ('FRUSTRATED', 'Frustrated'), ('CONSUMMATED', 'Consummated')], max_length=100, null=True),
        ),
    ]
