# Generated by Django 5.0.6 on 2026-02-08 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0016_add_offense_fields_to_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Report Submitted'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected'), ('resubmitted', 'Report Resubmitted'), ('edited', 'Report Edited')], max_length=20)),
                ('actor_name', models.CharField(max_length=200)),
                ('actor_role', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accidents.accidentreport')),
            ],
            options={
                'db_table': 'report_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
