# Generated by Django 5.0.6 on 2026-02-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0017_reportactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='offense_other',
            field=models.CharField(blank=True, help_text='Specify if Other is selected', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='offense_type_other',
            field=models.CharField(blank=True, help_text='Specify if Other is selected', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='offense',
            field=models.CharField(blank=True, choices=[('RECKLESS_IMPRUDENCE_DAMAGE_PROPERTY', 'Reckless Imprudence Resulting to Damage to Property - RPC Art 365'), ('RECKLESS_IMPRUDENCE_PHYSICAL_INJURY', 'Reckless Imprudence Resulting to Physical Injury - RPC Art 365'), ('RECKLESS_IMPRUDENCE_HOMICIDE', 'Reckless Imprudence Resulting to Homicide - RPC Art 365'), ('RECKLESS_IMPRUDENCE_MULTIPLE_PHYSICAL_INJURY', 'Reckless Imprudence Resulting to Multiple Physical Injury - RPC Art 365'), ('RECKLESS_IMPRUDENCE_MULTIPLE_DAMAGE_PROPERTY', 'Reckless Imprudence Resulting to Multiple Damage to Property - RPC Art 365'), ('RECKLESS_IMPRUDENCE_MULTIPLE_HOMICIDE', 'Reckless Imprudence Resulting to Multiple Homicide - RPC Art 365'), ('ANTI_DRUNK_DRUGGED_DRIVING', 'Anti-Drunk and Drugged Driving Act of 2013 - RA 10586'), ('LAND_TRANSPORTATION_TRAFFIC_CODE', 'Land Transportation and Traffic Code - RA 4136'), ('OTHER', 'Other')], help_text='Offense description', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='offense_type',
            field=models.CharField(blank=True, choices=[('CRIMES_AGAINST_PROPERTY', 'Crimes Against Property'), ('CRIMES_AGAINST_PERSONS', 'Crimes Against Persons'), ('REPUBLIC_ACT', 'Republic Act'), ('CRIMES_AGAINST_POPULAR_REPRESENTATION', 'Crimes Against Popular Representation'), ('CRIMES_AGAINST_PERSONAL_LIBERTY', 'Crimes Against Personal Liberty and Security'), ('PRESIDENTIAL_DECREE', 'Presidential Decree'), ('OTHER', 'Other')], help_text='Type of offense', max_length=300, null=True),
        ),
    ]
