# Generated by Django 5.0.6 on 2026-02-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0018_add_offense_choices_and_other_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
