# Generated by Django 5.0.6 on 2026-02-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0019_make_street_address_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_submitted', 'New Report Submitted'), ('report_approved', 'Report Approved'), ('report_rejected', 'Report Rejected'), ('report_cancelled', 'Report Cancelled'), ('info', 'Information')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reportactivitylog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Report Submitted'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected'), ('resubmitted', 'Report Resubmitted'), ('edited', 'Report Edited'), ('cancelled', 'Report Cancelled')], max_length=20),
        ),
    ]
