# Generated by Django 5.0.6 on 2026-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0020_add_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='drug_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accident',
            name='vehicle_chassis_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='vehicle_colorum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='drug_involved',
            field=models.BooleanField(default=False, help_text='Whether drugs/alcohol were involved'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_chassis_no',
            field=models.CharField(blank=True, help_text='Vehicle chassis/serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_colorum',
            field=models.BooleanField(default=False, help_text='Vehicle operating without franchise (colorum)'),
        ),
    ]
