# Generated by Django 5.0.6 on 2026-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0026_cleanup_auditlog_action_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('password_verify', 'Password Verified'), ('CHANGE_USERNAME', 'Username Changed'), ('FAILED_PASSWORD_CHANGE', 'Failed Password Change'), ('FAILED_USERNAME_CHANGE', 'Failed Username Change'), ('accident_create', 'Accident Created'), ('accident_edit', 'Accident Edited'), ('case_status_update', 'Case Status Updated'), ('user_create', 'User Created'), ('user_edit', 'User Edited'), ('user_status_change', 'User Status Changed'), ('user_profile_edit', 'User Profile Edited'), ('user_status_edit', 'User Status Edited'), ('username_change', 'Username Changed by Admin'), ('profile_picture_upload', 'Profile Picture Uploaded'), ('clustering_run', 'Clustering Executed'), ('clustering_complete', 'Clustering Completed'), ('clustering_failed', 'Clustering Failed'), ('export_data', 'Data Exported'), ('admin_dashboard_view', 'Admin Dashboard Viewed'), ('system_config', 'System Configuration Changed')], max_length=50),
        ),
    ]
