# Generated by Django 5.0.6 on 2026-04-12 00:35

import accidents.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0030_userprofile_can_submit_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo of accident scene (max 5MB, jpg/png)', upload_to='accident_reports/', validators=[accidents.validators.validate_image_file_size, accidents.validators.validate_image_file_extension])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accidents.accidentreport')),
            ],
            options={
                'db_table': 'report_photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
