# Generated by Django 5.0.6 on 2026-04-12 00:35

from django.db import migrations


def migrate_photos_forward(apps, schema_editor):
    AccidentReport = apps.get_model('accidents', 'AccidentReport')
    ReportPhoto = apps.get_model('accidents', 'ReportPhoto')

    for report in AccidentReport.objects.all():
        order = 0
        for field_name in ['photo_1', 'photo_2', 'photo_3']:
            photo = getattr(report, field_name)
            if photo:
                ReportPhoto.objects.create(
                    report=report,
                    image=photo.name,
                    order=order,
                )
                order += 1


def migrate_photos_backward(apps, schema_editor):
    AccidentReport = apps.get_model('accidents', 'AccidentReport')
    ReportPhoto = apps.get_model('accidents', 'ReportPhoto')

    for report in AccidentReport.objects.all():
        photos = ReportPhoto.objects.filter(report=report).order_by('order', 'uploaded_at')[:3]
        fields = ['photo_1', 'photo_2', 'photo_3']
        for i, photo in enumerate(photos):
            setattr(report, fields[i], photo.image.name)
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0031_add_report_photo_model'),
    ]

    operations = [
        migrations.RunPython(migrate_photos_forward, migrate_photos_backward),
    ]
