# Generated by Django 5.0.6 on 2026-04-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0032_migrate_photos_to_reportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='office',
            field=models.CharField(blank=True, help_text='For Provincial Chief (PPO) and Regional Director (PRO). Leave blank for station-level personnel.', max_length=200, null=True, verbose_name='Office/Command'),
        ),
    ]
