# Generated by Django 5.0.6 on 2026-04-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0033_add_office_field_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_run_clustering',
            field=models.BooleanField(default=False, help_text='Allow this user to run the hotspot clustering algorithm', verbose_name='Can Run Clustering'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, choices=[('', '--- Select Unit ---'), ('R1 - Regional Personnel and Records Management Division', 'R1 - Regional Personnel and Records Management Division'), ('R2 - Regional Intelligence Division', 'R2 - Regional Intelligence Division'), ('R3 - Regional Operation Management Division', 'R3 - Regional Operation Management Division'), ('R4 - Regional Logistics Research Development Division', 'R4 - Regional Logistics Research Development Division'), ('R5 - Regional Community Affairs Development Division', 'R5 - Regional Community Affairs Development Division'), ('R6 - Regional Comptrollership Division', 'R6 - Regional Comptrollership Division'), ('R7 - Regional Investigation Detective Management Division', 'R7 - Regional Investigation Detective Management Division'), ('R8 - Regional Learning and Doctrine Development Division', 'R8 - Regional Learning and Doctrine Development Division'), ('R9 - Regional Plans and Strategy Management Division', 'R9 - Regional Plans and Strategy Management Division'), ('Regional Headquarters Support Unit', 'Regional Headquarters Support Unit'), ('Regional Information and Communication Technology Management Division', 'Regional Information and Communication Technology Management Division'), ('Regional Health Service', 'Regional Health Service'), ('Public Information Office', 'Public Information Office'), ('Regional Mobile Force Battalion', 'Regional Mobile Force Battalion'), ('Regional Drug Enforcement Unit', 'Regional Drug Enforcement Unit'), ('Regional Highway Patrol Unit', 'Regional Highway Patrol Unit'), ('Regional Maritime Unit', 'Regional Maritime Unit'), ('Regional Criminal Investigation and Detection Unit', 'Regional Criminal Investigation and Detection Unit'), ('Regional Forensic Unit', 'Regional Forensic Unit'), ('Regional Special Operations Unit', 'Regional Special Operations Unit'), ('Women and Children Protection Center', 'Women and Children Protection Center'), ('Regional Internal Affairs Service', 'Regional Internal Affairs Service'), ('Regional Legal Service', 'Regional Legal Service'), ('Regional Finance Service', 'Regional Finance Service'), ('Regional Chaplain Service', 'Regional Chaplain Service'), ('Regional Communications and Electronics Unit', 'Regional Communications and Electronics Unit'), ('Regional Personnel Holding and Accounting Unit', 'Regional Personnel Holding and Accounting Unit')], max_length=200, null=True, verbose_name='Unit/Office'),
        ),
    ]
