# Generated by Django 5.0.6 on 2026-04-20 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0034_add_can_run_clustering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_reports',
            field=models.BooleanField(default=False, help_text='Allow this user to edit/submit accident report forms', verbose_name='Can Edit Report Form'),
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('incident_type', 'Incident Type'), ('type_of_place', 'Type of Place'), ('offense', 'Offense'), ('offense_type', 'Offense Type'), ('stage_of_felony', 'Stage of Felony'), ('vehicle_kind', 'Vehicle Type')], db_index=True, max_length=50)),
                ('value', models.CharField(help_text='Internal value (stored in DB)', max_length=300)),
                ('label', models.CharField(help_text='Display label shown to users', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-loaded from original system choices (cannot delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropdown_options_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dropdown Option',
                'verbose_name_plural': 'Dropdown Options',
                'ordering': ['field_name', 'sort_order', 'label'],
                'unique_together': {('field_name', 'value')},
            },
        ),
    ]
