# Generated by Django 5.0.6 on 2026-04-21 13:49

import accidents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0036_vehicle_hierarchy_and_felony_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='driver_license_no',
            field=models.CharField(blank=True, help_text="Driver's license number", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='hospital_taken_to',
            field=models.CharField(blank=True, help_text='Hospital victim was taken to', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_address_barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_address_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_address_village',
            field=models.CharField(blank=True, help_text='Village/Sitio', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_citizenship',
            field=models.CharField(blank=True, default='Filipino', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_civil_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_home_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_id_presented',
            field=models.CharField(blank=True, help_text='ID card presented', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_other_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_qualifier',
            field=models.CharField(blank=True, help_text='Jr./Sr./III etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='sketch_image',
            field=models.ImageField(blank=True, help_text='Sketch of the accident scene (max 5MB, jpg/png)', null=True, upload_to='accident_sketches/', validators=[accidents.validators.validate_image_file_size, accidents.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='suspect_address',
            field=models.TextField(blank=True, help_text='Current address of suspect', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='suspect_relation_to_victim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_or_cr_no',
            field=models.CharField(blank=True, help_text='Official Receipt / Certificate of Registration No.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_registered_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicles_data',
            field=models.JSONField(blank=True, default=list, help_text='Additional vehicles [{kind, make, model, plate_no, chassis_no, registered_owner, or_cr_no}]'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victim_address',
            field=models.TextField(blank=True, help_text='Current address of victim', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='victim_work_address',
            field=models.TextField(blank=True, help_text='Work address of victim', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='witnesses_data',
            field=models.JSONField(blank=True, default=list, help_text='List of witnesses [{name, age, address, contact}]'),
        ),
        migrations.AlterField(
            model_name='dropdownoption',
            name='parent_value',
            field=models.CharField(blank=True, default='', help_text='Parent option value for hierarchical fields (e.g., vehicle_make parent is vehicle_kind value)', max_length=300),
        ),
    ]
