# Generated by Django 5.0.6 on 2026-04-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0037_irf_alignment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_same_as_officer',
            field=models.BooleanField(default=False, help_text='If True, the reporting person is the investigating officer'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='reporter_contact',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='reporter_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
