# Generated by Django 5.0.6 on 2026-04-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0039_rename_reporter_same_to_has_complainant'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='blotter_number',
            field=models.PositiveIntegerField(blank=True, help_text='Traffic Police Blotter Entry No. — auto-incremented on approval', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='has_complainant',
            field=models.BooleanField(default=False, help_text='Whether a civilian complainant reported this incident'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='reporter_contact',
            field=models.CharField(blank=True, default='', help_text='Complainant contact number', max_length=50),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='reporter_name',
            field=models.CharField(blank=True, default='', help_text='Complainant full name', max_length=200),
        ),
    ]
