# Generated by Django 5.0.6 on 2026-04-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0040_add_blotter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Action taken by responding officer', null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='cause_of_accident',
            field=models.CharField(blank=True, choices=[('OVER_SPEEDING', 'Over Speeding'), ('DRUNK_DRIVING', 'Drunk Driving'), ('RECKLESS_DRIVING', 'Reckless Driving'), ('MECHANICAL_FAILURE', 'Mechanical Failure / Defect'), ('DRIVER_FATIGUE', 'Driver Fatigue'), ('DISTRACTED_DRIVING', 'Distracted Driving'), ('POOR_ROAD_CONDITION', 'Poor Road Condition'), ('POOR_VISIBILITY', 'Poor Visibility'), ('OVERTAKING', 'Improper Overtaking'), ('DISREGARD_TRAFFIC_SIGNS', 'Disregard of Traffic Signs/Signals'), ('PEDESTRIAN_ERROR', 'Pedestrian Error'), ('ANIMAL_ON_ROAD', 'Animal on Road'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='cause_of_accident_other',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='light_condition',
            field=models.CharField(blank=True, choices=[('DAYLIGHT', 'Daylight'), ('DUSK_DAWN', 'Dusk / Dawn'), ('DARK_LIGHTED', 'Dark (Street Lighted)'), ('DARK_UNLIGHTED', 'Dark (Not Lighted)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='road_character',
            field=models.CharField(blank=True, choices=[('STRAIGHT_FLAT', 'Straight & Flat'), ('STRAIGHT_GRADE', 'Straight & Grade'), ('CURVE_FLAT', 'Curve & Flat'), ('CURVE_GRADE', 'Curve & Grade')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='road_condition',
            field=models.CharField(blank=True, choices=[('DRY', 'Dry'), ('WET', 'Wet'), ('MUDDY', 'Muddy'), ('FLOODED', 'Flooded'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='weather_condition',
            field=models.CharField(blank=True, choices=[('CLEAR', 'Clear'), ('CLOUDY', 'Cloudy'), ('RAINY', 'Rainy'), ('FOGGY', 'Foggy'), ('WINDY', 'Windy'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
